#!/usr/bin/python

import argparse
import errno
import shutil
import os

basedir = os.path.dirname(os.path.realpath(__file__))

mapping = {
    '.tmux.conf': '~/.tmux.conf',
    '.tmux': '~/.tmux',
    '.gitconfig': '~/.gitconfig',
    '.bash_aliases': '~/.bash_aliases',
    '.bash_functions': '~/.bash_functions',
    '.bashrc': ['~/.bashrc', '~/.bash_profile'],
    '.bash_colors': '~/.bash_colors',
    '.Xmodmap': '~/.Xmodmap',
    'i3.conf': '~/.i3/config',
    '.i3status.conf': '~/.i3status.conf',
    'termite.conf': '~/.config/termite/config',
    '.xonshrc': '~/.xonshrc',
    '.xonsh_functions.xsh': '~/.xonsh_functions.xsh',
    '.xonsh_aliases.xsh': '~/.xonsh_aliases.xsh',
    'ack.rc': '~/.ackrc',
    'chunkwmrc': '~/.chunkwmrc',
    '.alacritty.yml': '~/.alacritty.yml',
}


def mkdir_p(path):
    try:
        os.makedirs(path)
    except OSError as exc:
        if exc.errno != errno.EEXIST or not os.path.isdir(path):
            raise


def try_dist_file(f, src, dst):
    src_path = os.path.join(basedir, src)
    dst_path = os.path.expanduser(dst)
    print('{0} -> {1}'.format(src_path, dst_path))


    try:
        mkdir_p(os.path.dirname(dst_path))
        f(src_path, dst_path)
    except OSError as msg:
        print('\twarning: unable to distribute: ' + str(msg))


def distribute_files(f):
    for src, dst in mapping.items():
        dst = [dst] if not isinstance(dst, list) else dst
        for d in dst:
            try_dist_file(f, src, d)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Destribute .dotfiles')
    parser.add_argument('--copy', action='store_true')
    args = parser.parse_args()

    dist_func = shutil.copy2 if args.copy else os.symlink
    distribute_files(dist_func)
